import Link from 'next/link';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function ReaderLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white shadow">
        <div className="container mx-auto px-4 py-4 flex justify-between items-center">
          <Link href="/reader" className="text-xl font-bold text-blue-700">
            SFL (Small Free Library)
          </Link>
          <nav className="flex space-x-6">
            <Link href="/reader" className="text-gray-700 hover:text-blue-700">
              Books
            </Link>
            <Link href="/reader/history" className="text-gray-700 hover:text-blue-700">
              My History
            </Link>
            <Link href="/reader/donate" className="text-gray-700 hover:text-blue-700">
              Donate
            </Link>
          </nav>
        </div>
      </header>
      <main className="container mx-auto py-4">
        {children}
      </main>
    </div>
  );
}